use_frameworks!

target 'QuicklyQR_Example' do
  pod 'QuicklyQR', :path => '../'

  target 'QuicklyQR_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
